// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddService(arg1:main.ServiceConfig):Promise<main.Service>;

export function ClearLogs(arg1:string):Promise<void>;

export function GetService(arg1:string):Promise<main.ServiceInfo>;

export function GetServices():Promise<Record<string, main.ServiceInfo>>;

export function ReloadServices():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function UpdateService(arg1:string,arg2:main.ServiceConfig):Promise<main.Service>;
