// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddService(arg1) {
  return window['go']['main']['App']['AddService'](arg1);
}

export function ClearLogs(arg1) {
  return window['go']['main']['App']['ClearLogs'](arg1);
}

export function GetService(arg1) {
  return window['go']['main']['App']['GetService'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function ReloadServices() {
  return window['go']['main']['App']['ReloadServices']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function UpdateService(arg1, arg2) {
  return window['go']['main']['App']['UpdateService'](arg1, arg2);
}
